name: simply_qrcode
version: 1.1.0+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: 4.6.6
  image_gallery_saver: ^2.0.3
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
